export default {
    REQUEST: 'REQUEST',
    country: {
        COUNTRY_LOADING: 'COUNTRY_LOADING',
        COUNTRY_LOADED: 'COUNTRY_LOADED',
        COUNTRY_LOAD_FAILURE: 'COUNTRY_LOAD_FAILURE'
    },
    user: {
        profile: {
            PROFILE_LOADING: 'PROFILE_LOADING',
            PROFILE_LOADED: 'PROFILE_LOADED',
            PROFILE_LOAD_FAILURE: 'PROFILE_LOAD_FAILURE'
        }
    },
    project: {
        PROJECTS_LOADING: 'PROJECTS_LOADING',
        PROJECTS_LOADED: 'PROJECTS_LOADED',
        PROJECTS_LOAD_FAILURE: 'PROJECTS_LOAD_FAILURE'
    },
    article: {
        ADD: 'ADD',
        UPDATE: 'UPDATE',
        DELETE: 'DELETE',
        ARTICLE_BY_PROJECT_LOADING: 'ARTICLE_BY_PROJECT_LOADING',
        ARTICLE_BY_PROJECT_LOADED: 'ARTICLE_BY_PROJECT_LOADED',
        ARTICLE_BY_PROJECT_LOAD_FAILURE: 'ARTICLE_BY_PROJECT_LOAD_FAILURE'
    }
};
