export default {
    REQUEST: 'REQUEST',
    country: {
        COUNTRY_LOADING: 'COUNTRY_LOADING',
        COUNTRY_LOADED: 'COUNTRY_LOADED',
        COUNTRY_LOAD_FAILURE: 'COUNTRY_LOAD_FAILURE'
    }
};
