export const EVENTS = {
    ON_VALIDATE: 'ON_VALIDATE',
    ON_VALIDATE_SUCCESS: 'ON_VALIDATE_SUCCESS',
    ON_VALIDATE_FAILURE: 'ON_VALIDATE_FAILURE',
    OPERATED_NOTIFICATION: {
        SHOW: 'OPERATED_NOTIFICATION_SHOW',
        HIDE: 'OPERATED_NOTIFICATION_HIDE'
    }
};
